### ISSUE TITLE
Cannot kick off dev server for examples

### ISSUE THREAD

**Issue by SQuirreL4niner** [michalochman/react-pixi-fiber#10]
### Description
Thanks for supporting this library as I'm fairly new to React and HTML gaming!

Using Windows 10 Pro
Installed Yarn via Chocolatey
* Also had to install Babel globally via npm to fix initial build error

Follow the instruction via readme to run examples and get error - 

Module not found: Can't resolve './dist/react-pixi-fiber.development.js' in '...\fiberdemo\react-pixi-fiber\node_modules\react-pixi-fiber'

### Steps to reproduce

1. yarn install or npm install from examples directory
2. yarn start or npm start from examples directory
3. server loads and serves to port 3000 but above error is shown

### Additional info

- React version: 16.2.0
- ReactDOM version: 16.2.0
- PixiJS version: 4.4.0

**Comment by michalochman** [comment]
@SQuirreL4niner thanks for reporting, turns out that there was issue with missing `dist` folder.

Please pull the latest `master` branch and retry running `yarn` or `npm install` in the repository root and then the rest of the steps.
