### ISSUE TITLE
Cant access ticker with context

### ISSUE THREAD

**Issue by jjarrett21** [michalochman/react-pixi-fiber#101]
I would like the animations to run off of my own timer, however I can not find documentation for hijacking ticker, and every time I try and call this.props.app.ticker(this.animate) I get undefined errors. Need Help. SOS!

**Comment by jjarrett21** [comment]
Adding some code for more info:

`class PixiRectangle extends Component {

    state = {
        x: 0,
        rectangles
    };

    componentDidMount() {
        // this.props.app.ticker.add(this.animate)

    }

    componentWillMount() {
        // this.props.app.ticker.remove(this.animate);
    }

    timerStart () {
        this.props.app.ticker.add(this.animate)
    }

    timerStopper () {
        this.props.app.ticker.stop(this.animate)
    }

    animate = (delta) => {

        if(this.state.x < 640) {
            this.setState(state => ({ 
                ...state,
                x: state.x + 1 * delta,
            }));
        } else {
            this.state.x = 0
        }
    };

    render() {
        return (
            rectangles.map((rect) => (
                <Rectangle key={rect.id} {...rect} x={this.state.x} />
            ))
        );
    }
}`


`   Timer = (time) => {
        console.log('Timer time: ',time)
        timeDelta = wallClock - time

        generateRectangles(rectangles, randomRect)
       
    
        requestIdleCallback(() => {
            this.setState({ time })
        })
    
        this.animationID = requestAnimationFrame(this.Timer);
    }
    

    playPause = () => {
        var playing = !this.state.playing
        let pr = new PixiRectangle
        var start = pr.timerStart()
        var stop = pr.timerStopper()
        this.setState({ playing }, () => {
            if (playing) {
                //this.Timer()
                start()

            } else {
                cancelAnimationFrame(this.animationID)
                stop() 
            }
        })

    }`

**Comment by michalochman** [comment]
Hi @jjarrett21, please put the example code that you think is not working on e.g. codesandbox.io so we can see it in action.

**Comment by jjarrett21** [comment]
I think I figured it out, thanks.
