### ISSUE TITLE
removeChild

### ISSUE THREAD

**Issue by jjarrett21** [michalochman/react-pixi-fiber#102]
I am trying to conditionally remove some rectangles that I'm mapping before hand using the .removeChild and it keeps telling me that it is not a function, is the stage. remove not a function?

**Comment by michalochman** [comment]
@jjarrett21 that's not how you use React, if you don't want to render some elements from a list then `filter` before `map`. If you want to skip react then refer to [PIXI docs](http://pixijs.download/release/docs/index.html).
