### ISSUE TITLE
DisplacementFilter in react-pixi-fiber

### ISSUE THREAD

**Issue by yvesvinckier** [michalochman/react-pixi-fiber#103]
### Description
is it possible to deal with DisplacementFilter in react-pixi-fiber to do a ripple effet.
to do something like that : 
// get our displacement map (image)	
    var displacementSprite = PIXI.Sprite.fromImage("images/filters/water.png");
    // set to repeat in a tiled patern
   displacementSprite.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;	
   // set filter to sprite container
    var displacementFilter = new PIXI.filters.DisplacementFilter(displacementSprite);

   // Add our filter and sprites to stage		
    stage.filters = [displacementFilter];
    stage.addChild(displacementSprite);
    stage.addChild(image);

Thanks for your answer
Yves

**Comment by michalochman** [comment]
@yvesvinckier a quick 5 minute demo: https://codesandbox.io/s/8813o9o4j8

This is not the cleanest solution, but should give you an idea of one way to approach this. If you want the code to be more react-like (i.e. declarative), I would create [Custom Component](https://github.com/michalochman/react-pixi-fiber#custom-components) with all the imperative code instead.

**Comment by KevinSeghetti** [comment]
I am looking for information on using PIXI filters, and writing custom shaders, through react-pixi-fiber. 
The code sandbox linked above just shows the background color, so has somehow broken since it was created. 
Is there a functioning example I could look at?
(Also, be nice to have an example using react hooks instead of a react class).

**Comment by michalochman** [comment]
@KevinSeghetti I have updated the codepen to not use external images (this was an issue) and to use the newest version available.
