### ISSUE TITLE
TypeError calling PIXI.Texture.fromImage

### ISSUE THREAD

**Issue by xtaaaal** [michalochman/react-pixi-fiber#106]
### Description
I'm starting up an app and try to render a sprite but getting following error:

```
TypeError: pixi_js__WEBPACK_IMPORTED_MODULE_3__.Texture.fromImage is not a function


   5 | import man from "./../asset/img/man09.png";
   6 | 
   7 | function StaticMan(props) {
 > 8 |   return <Sprite texture={PIXI.Texture.fromImage(man)} {...props} />;
   9 | }
  10 | 
```

### Steps to reproduce

1. `npx create-react-app {my-app}`
2. `npm install pixi.js`
3.  `npm install react-pixi-fiber --save`
4.  create a function and attemp to get the pixi texture
```
 function StaticMan(props) {
  return <Sprite texture={PIXI.Texture.fromImage(man)} {...props} />;
}
```
5. `npm start` to run the app

### Additional info

- react-pixi-fiber version: 0.8.0
- React version: 6.4.1
- ReactDOM version: 16.8.6
- PixiJS version: 5.0.2

**Comment by michalochman** [comment]
Hi @xtaaaal, looks like you’re using Pixi v5, which now has `
PIXI.Texture.from` method instead.

**Comment by xtaaaal** [comment]
Thanks a lot! It works now!
