### ISSUE TITLE
Can you make it run with PixiJS version 5.0.2?

### ISSUE THREAD

**Issue by inglesuniversal** [michalochman/react-pixi-fiber#108]
Best regards

**Comment by michalochman** [comment]
@inglesuniversal what is not working for you? Can you be more specific?

I can see it working with PixiJS@5.0.3, see this [codesandbox](https://codesandbox.io/s/quiet-frog-sjqf7).

**Comment by inglesuniversal** [comment]
Thanks. I works now. I simply tried to change the version on the sandbox json file.
