### ISSUE TITLE
Adding "react-pixi-fiber" to build via "yarn add react-pixi-fiber" fails to install.

### ISSUE THREAD

**Issue by tarqu1n** [michalochman/react-pixi-fiber#11]
### Description
Adding "react-pixi-fiber" to build via "yarn add react-pixi-fiber" fails to install.

### Steps to reproduce

First it failed with `'babel' is not recognized as an internal or external command.` so i installed the babel cli

After this it runs `babel src/ReactPixiFiber.js -o dist/react-pixi-fiber.development.js`

which seems to succeed, then the following error is given.

`Error: ENOENT: no such file or directory, open '...react-sandbox\node_modules\react-pixi-fiber\dist\react-pixi-fiber.development.js'`

### Additional info
package.json:

    "jquery": "^3.2.1",
    "pixi.js": "^4.6.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.0",
    "three": "^0.89.0"

Have tried this on two machines, one of which already had babel installed. Same result for each. Build is a fresh react install.

**Comment by michalochman** [comment]
I‘ll try to sort out #4 today, because that’s the root issue.

**Comment by michalochman** [comment]
@tarqu1n should work now, let me know if you have any issues.
