### ISSUE TITLE
PIXI.Point.copy() deprecated in v5, causes setPixiValue() to break

### ISSUE THREAD

**Issue by SenHeng** [michalochman/react-pixi-fiber#120]
### Description

http://pixijs.download/release/docs/PIXI.Point.html#copy

https://github.com/michalochman/react-pixi-fiber/blob/42c2522c67d173a79b708e4dae24584b82ba4afe/src/utils.js#L60

Managed to fix by updating `copy` to `copyFrom`.

I could push a PR that checks for whichever exists and use it if you're ok with that, unless you have something else planned?

### Steps to reproduce

Not my codebase but roughly something like this

```
import { Text } from 'react-pixi-fiber';
...
render = () => {
    return (
      <Text
        position={new Point(1 ,1)}
      />
    );
  };
``` 

### Additional info

- react-pixi-fiber version: 0.8.1
- React version: 16.8.5
- ReactDOM version: 16.8.5
- PixiJS version: 5.0.4

**Comment by michalochman** [comment]
Thanks @SenHeng, `copyFrom` is not available in Pixi v4, so if you could add a check for existence of either of those that would be great!
