### ISSUE TITLE
Functional Component child of Stage doesn't work with Hooks

### ISSUE THREAD

**Issue by DanProudfoot** [michalochman/react-pixi-fiber#122]
### Description

Using a component as a child of Stage means I can't use hooks in that component. 

### Steps to reproduce

I've created a [codesandbox that replicates the problem](https://codesandbox.io/s/eager-wescoff-hwmkv?fontsize=14). You'll have to open the external page view because it was complaining about WebGL otherwise. 

In the console output of the external page, you should see 

> Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. 

Even though quite clearly it's a functional component. I don't seem to get this problem on any hook called outside of Stage, so I can only guess something screwy is going on.

### Additional info

- react-pixi-fiber version: 0.8.1
- React version: 16.8.6
- ReactDOM version: 16.8.6
- PixiJS version: 5.0.4

**Comment by michalochman** [comment]
Thanks for reporting and reproduction scenario @DanProudfoot, I'll investigate.

**Comment by SenHeng** [comment]
Receiving the same error after updating react-redux to v7.1.0 from v6.
Reverting to v6.0.1 fixes the issue.

![スクリーンショット 2019-07-01 14 49 27](https://user-images.githubusercontent.com/11208360/60413312-6f76a600-9c0f-11e9-9762-c6a8730aac48.png)

 ### packages
 * react-pixi-fiber version: 0.8.1
 * React version: 16.8.6
 * React-redux: 7.1.0
 * ReactDOM version: 16.8.6
 * PixiJS version: 4.8.8

**Comment by michalochman** [comment]
@DanProudfoot I think it should be fixed in v0.9.0, please reopen if it's not.

@SenHeng I have not checked it with react-redux@7.1.0 but if the issue was the same then it should work as well. Please open separate issue if it's not.

**Comment by DanProudfoot** [comment]
Yep, that worked. Thanks for getting that fixed.
