### ISSUE TITLE
typescript withApp is missing

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#125]
### Description
Works as expected apart type definition for `withApp` is missing

<img width="634" alt="image" src="https://user-images.githubusercontent.com/3826097/60714376-e2836380-9f12-11e9-8109-4a4095314c97.png">

### Additional info

"react-pixi-fiber": "^0.9.0",
"react-resize-detector": "^4.0.5"

**Comment by kresli** [comment]
My bad. I'm using 16.8.x where docs clearly says 
> Using withApp Higher-Order Component (with React <16.3.0 and React >=16.3.0)

**Comment by michalochman** [comment]
@kresli `withApp` should work regardless of React version you're using, it's missing from typescript definitions which I'm not maintaining personally (they were contributed by others) so yeah, it's still an issue, reopening.

**Comment by michalochman** [comment]
@kresli can you check if #133 fixes your issue?
