### ISSUE TITLE
Q: How to use class instance as behaviour

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#126]
Its seems like the behaviour customApplyProps ( and maybe other lifecycle methods) are bound to parent scope which is stoping me to use class instance as parameter for CustomPIXIComponent. Maybe I just missing something here. If this is expected, would anyone mind to explain me why its bind to parent instance?
Thanks

```ts
class Rect {
  private instance: PIXI.Graphics;
  public customApplyProps = (instance, oldProps, newProps) => {
    console.log("this.instance is equal", this.instance === instance); // false but it should be true
    // following demonstrate this is bound to parent not to current scope
    if (this.instance.children.length > 0) {
      console.log("this === parent : ", this.instance.children[0] === instance); // true but it should be false;
    }
  };
  public customDisplayObject = props => {
    this.instance = new PIXI.Graphics();
    return this.instance;
  };
}

const TYPE = "Rectangle";
export const Rectangle = CustomPIXIComponent<{}, PIXI.Graphics>(
  new Rect(),
  TYPE
);
```

**Comment by michalochman** [comment]
Hi @kresli, can you create more comprehensive example, for example on [codesandbox.io](https://codesandbox.io)? The code above doesn't even compile.

Also it would help if you could explain why you need class instance in this scenario.

**Comment by kresli** [comment]
I apologise for very bad example. Here is working demo https://codesandbox.io/s/epic-meadow-9qk82
Open console click `increment` button in editor and you'll see second Rectangle level is bound to parent

**Comment by michalochman** [comment]
I can see the issue now.

`customDisplayObject` was never thought to be a class bound method – for historical reasons (compatibility with original react-pixi lib), custom components had access to [applyDisplayObjectProps method](https://github.com/Izzimach/react-pixi/blob/a25196251a13ed9bb116a8576d93e9fceac2a14c/src/ReactPIXI.js#L953). For this reason, `this` should be [an object with `applyDisplayObjectProps` method](https://github.com/michalochman/react-pixi-fiber/blob/57a7d025fadbb6fd6276a47e5a88d0450b13e86a/src/inject.js#L27) that is bound to a PIXI instance.

Can you explain why you want the behaviour definition to be a class instance? How are you going to use it in real project? Perhaps we can figure out what should be the solution.

**Comment by kresli** [comment]
well its more about simple OOP. So here is something which I try to do

```ts
abstract class Component<P extends {x: number, y: number}> {
      protected props!: P;
      protected container!: ComponentContainer;
      protected instance!: PIXI.Graphics;
      private gizmo!: PIXI.Graphics;
      public abstract gizmoSize(): Gizmo;
    
      public customDisplayObject = (props: P) => {
        this.props = props;
        const container = new PIXI.Container() as ComponentContainer;
        const gizmo = new PIXI.Graphics();
        const instance = new PIXI.Graphics();
        container.rcfComponent = this;
        container.addChild(instance);
        container.addChild(gizmo);
        this.gizmo = gizmo;
        this.container = container as ComponentContainer;
        this.instance = instance;
        return container;
      }
      public customApplyProps = (
        container: ComponentContainer,
        b: any,
        newProps: P,
      ) => {
        this.props = newProps;
        this.container.x = this.props.x;
        this.container.y = this.props.y;
        this.container.rcfComponent = this;
        if (!this.isHidden()) {
          this.render();
        } else {
          this.instance.clear();
        }
        this.renderGizmo();
      }
      public customDidAttach = () => {};
      public abstract render(): void;
      private isHidden = () => {
        const { width, height } = this.gizmoSize();
        const { x, y } = this.props;
        if (this.container.parent && this.container.parent.rcfComponent) {
          const parentBounds = this.container.parent.getLocalBounds();
          if (
            x < -width ||
            x > this.container.parent.rcfComponent.gizmoSize().width ||
            y < -height ||
            y > parentBounds.height
          ) {
            return true;
          }
        }
        return false;
      }
    
      private renderGizmo() {
        const { width, height, x, y } = this.gizmoSize();
        this.gizmo.clear();
        if (!this.props.showGizmo) {
          return;
        }
        this.gizmo.beginFill(0x000000, 0);
        this.gizmo.lineStyle(1, 0xffff00);
        this.gizmo.drawRect(x, y, width, height);
      }
    }

    class Rectangle extends Component<{x: number, y: number}> {
        render() {
            // lets  draw this.instance
        }
    }
```
The basic idea is render Bounding box around graphic and once child bounding box is outside parent, stop rendering. Also I like to include something like mobX in my classes for better performance. Its just an experiment to see the possibilities of the package.

**Comment by michalochman** [comment]
Hi @kresli the code you presented is not what you would usually do with React which is all about prefering composition over inheritance.

The way I see it, you are trying to create custom component that basically manages multiple PixiJS entities which makes the code overly complicated and not extensible (e.g. what would you do if you want the child to be Sprite instead of Graphics?).

Not sure if I understand your problem correctly, but you can see how I would usually approach this in React [in this example](https://codesandbox.io/s/react-pixi-fiber-github-issue-126-mbqdu) – just click anywhere on the stage to change purple square position, it will not be rendered when completely outside white bounding box. It is of course a naive and simplified solution, but is enough just to illustrate what you can do with composition.

**Comment by kresli** [comment]
Yep I agree with unusual approach. React is pushing for composting over inheritance.  But pixi on other hand has no issue with inheritance. This is unique approach and I understand there is very few users who like to use class based react-pixi components. I was more wonder why the scope is bound to different scope in middle of process which is always a bad idea ( in my humble opinion). If you need access inner scope, you'll still can pass it as argument. If you think this is not an issue, feel free to close this issue. Thank you for looking into it :)

**Comment by michalochman** [comment]
Simple answer is – it's because this package was meant to be a replacement for [react-pixi](https://github.com/Izzimach/react-pixi) that only supported React versions up to 15. When I was building react-pixi-fiber I wanted an easy way to port my large codebase to React 16. You can see a few tricks here and there only because of backwards compatibility or because react-pixi did something one way or another.

If you can propose `CustomPIXIComponent` implementation that will work with both scenarios then I'm happy to accept and merge PR.

**Comment by lekzd** [comment]
my workaround for this situation:

1. make a helper function createCustomComponent
```
export const createCustomComponent = <
  T extends DisplayObject = DisplayObject,
  P extends {} = {}
>(
  name: string,
  customDisplayObject: (props: P) => T
) => {
  const behavior = {
    customDisplayObject,
    customApplyProps: (instance: T, old: P | undefined, props: P) => {
      Object.assign(instance, props)
    },
  }

  return CustomPIXIComponent(behavior, name)
}
```

2. use it as component inside another one React component to have a state, lifecycle, etc
```
export const MyWrapper = () => {
   const MyGraphics = useMemo(() => createCustomComponent('MyGraphics', () => new Graphics())), [])
   
   return <MyGraphics  />
}
```
