### ISSUE TITLE
Testing with react testing library throw  PascalCase naming warning 

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#129]
### Description

Using https://github.com/testing-library/react-testing-library
throw warning 
<img width="892" alt="image" src="https://user-images.githubusercontent.com/3826097/61330850-7b21b980-a818-11e9-8e0d-f9a77258c871.png">
It's just an warning per component but it get's annoying if test contain many fiber components
### Steps to reproduce

1. clone https://github.com/kresli/react-pixi-fiber-broken-test-camel-casing
2. follow readme (run test)

### Additional info

    "pixi.js": "5.0.4",
    "react": "16.8.4",
    "react-dom": "16.8.4",
    "react-pixi-fiber": "0.9.0"

**Comment by michalochman** [comment]
Hi @kresli, this warning seems wrong, it should only apply to DOM elements, not to React Pixi Fiber elements. Is there a way to get rid of it somehow? It doesn't happen when using plain `jest` for testing.

I was thinking about changing `Container` to `container` for 1.0 release (it would be breaking change), but I think this warning should not apply here anyway.

**Comment by kresli** [comment]
No clue, I hoped you'll know. I looked into it and you're right, the error doesn't seems right. I'll take another look once I'm free from other stuff I'll need your help to understand how fiber component are created. One thing related to the issue is creating a component with dot notation like `component.Container` not sure if that's happening in your project.

**Comment by kresli** [comment]
Ok, seems like once I set Stage warning goes away. eg 
```tsx
import { Container, Stage } from "../src/index";
import { render } from "@testing-library/react";
import * as React from "react";

test("Container is defined", () => {
  const container = render(
    <div>
      <Stage>
        <Container />
      </Stage>
    </div>
  );
  expect(container).toMatchSnapshot();
});
```

**Comment by michalochman** [comment]
Ah, if you've not been rendering it as a child of `Stage` then it was rendered by `ReactDOM`, not `ReactPixiFiber` and that would explain the warning.

**Comment by PByH** [comment]
> Ok, seems like once I wrap it with Stage warning goes away. eg

I have faced with a problem, my simple test always throws this error:
` WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.`
Here is an example forked from react-pixi-fiber-template:
https://codesandbox.io/s/loving-firefly-rgh4w
As far as I understand, this error appears because jest uses browser-like environment which has no ability to test webgl rendering. 
Am I use wrong renderer?

**Comment by michalochman** [comment]
Hi @PByH, try this: https://github.com/michalochman/react-pixi-fiber/blob/develop/config/jest.dev.json#L8-L10

**Comment by PByH** [comment]
Thanks a lot for quick answer! 
I've added pixi.js-legacy to package.json both in devDependencies and "moduleNameMapper", but there is another error:
TypeError: Cannot read property 'AccessibilityManager' of undefined
I've spent a couple of hours to fix that, but there is no success. I've created a repo with a sample project:
https://github.com/PByH/react-pixi-fiber-ts-jest
I'm so grateful if somebody helps me with tests launching.

**Comment by PByH** [comment]
Oh, I finally did it!)
Version with working tests is committed in repo from my previous comment.
Thanks a lot for this great library!

**Comment by michalochman** [comment]
@PByH great to hear that you managed to get it working. Would you be able to briefly let others know what you did in the comment here just in case you repo is gone? :)

**Comment by PByH** [comment]
@michalochman Sure :)
I've created a file named "pixi.js" in a project root:
```
export * from 'pixi.js-stable';
export { renderer } from 'pixi.js-legacy';
```
then I modified jest config in package.json
```
  "jest": {
    "moduleNameMapper": {
      "pixi.js$": "<rootDir>/pixi.js",
      "pixi.js-stable$": "<rootDir>/node_modules/pixi.js"
    }
  }
```
This solution is described in this tread: https://github.com/inlet/react-pixi/issues/126
