### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by eulertour** [michalochman/react-pixi-fiber#130]
The README for this repo states that it isn't production ready, but no justification is given and the blame indicates that it was written 2 years ago. Has this changed, and if not can you explain why?

**Comment by michalochman** [comment]
Hi @eulertour, I'm using this on production for almost 2 years without any issues (that couldn't be solved one way or another) so you're right – this text should not be in README any longer. Feel free to submit PR if you want as I'll not be able to push anything in the next few days.
