### ISSUE TITLE
<Graphics/>

### ISSUE THREAD

**Issue by robclouth** [michalochman/react-pixi-fiber#136]
There doesn't appear to be any draw method or anything with the Graphics component. The only way seems to be with a custom component. What's the point in the Graphics component then? Am I missing something?

**Comment by michalochman** [comment]
Hi @robclouth, there is no method like this for [PIXI.Graphics](https://pixijs.download/dev/docs/PIXI.Graphics.html) object, but you can use [`ref` prop](https://reactjs.org/docs/refs-and-the-dom.html) to access the underlying instance and do what you need.

Thanks for asking though! I think that adding `draw` method like you suggest might not be a bad idea after all. However, to do so, we would have to change the way Graphics component is instantiated. It is not as straightforward as it sounds though – while it should be easy to create an object that will just call supplied `draw` function, there are some issues to consider like memory leaks.

**Comment by ryanking1809** [comment]
I hope you don't mind me suggesting an api for this but it would be really useful to extend the `<Graphics />` component.

I was thinking you could map all `draw` functions to a component like so:
```jsx
<Graphics>
    <Rect 
        fill={{ color: 0xDE3249 }} 
        x={50} 
        y={50} 
        width={100} 
        height={100} 
    />
    <Star 
        lineStyle={{width: 2, color: 0xFEEB77}} 
        fill={{ color: 0x55335A, alpha: 1 }} 
        x={470} 
        y={450} 
        points={4} 
        radius={50} 
    />
    <Polygon 
        lineStyle={{width: 0}} 
        fill={{ color: 0x3500FA, alpha: 1 }} 
        path={[600, 370, 700, 460, 780, 420, 730, 570, 590, 520]} 
    />
</Graphics>
```
Which would produce something like this in Pixi
```js
const graphics = new PIXI.Graphics();

graphics.beginFill(0xDE3249);
graphics.drawRect(50, 50, 100, 100);
graphics.endFill();

graphics.lineStyle(2, 0xFEEB77);
graphics.beginFill(0x650A5A, 1);
graphics.drawStar(470, 450, 4, 50);
graphics.endFill();

graphics.lineStyle(0);
graphics.beginFill(0x3500FA, 1);
graphics.drawPolygon([600, 370, 700, 460, 780, 420, 730, 570, 590, 520]);
graphics.endFill();
```

It gets a little more tricky when it comes to just drawing paths. I like the idea of implementing some sort of `<Path />` component like so:
```jsx
<Graphics>
    <Path
        lineStyle={{width: 10, color: 0xFF0000, alpha: 0.8}} 
        fill={{color: 0xFF700B, alpha: 1}}
        path={[
            ["MoveTo", { x:210, y: 300 }]
            ["LineTo", { x:210, y: 300 }]
            ["LineTo", { x:210, y: 300 }]
            ["QuadraticCurveTo", { cpX:600, cpY: 0, toX:480, toY: 100 }]
            ["LineTo", { x:210, y: 300 }]
            ["LineTo", { x:210, y: 300 }]
            ["LineTo", { x:210, y: 300 }]
            ["ClosePath"]
        ]}
    />
</Graphics>
```
But maybe it's better to pull out the `lineStyle` and `fill` to be closer to Pixi's syntax?
```jsx
<Graphics>
    <LineStyle width={10} color={0xFF0000} alpha={0.8}/>
    <Fill color={0xFF700B} alpha={1}>
        <MoveTo x={210} y={300} />
        <LineTo x={450} y={320} />
        <LineTo x={570} y={350} />
        <QuadraticCurveTo cpX={600} cpY={0} toX={480} toY={100} />
        <LineTo x={330} y={120} />
        <LineTo x={410} y={200} />
        <LineTo x={210} y={300} />
        <ClosePath />
    </Fill>
</Graphics>
```
Producing
```js
const graphics = new PIXI.Graphics();
graphics.lineStyle(10, 0xFF0000, 0.8);
graphics.beginFill(0xFF700B, 1);
graphics.moveTo(210, 300);
graphics.lineTo(450, 320);
graphics.lineTo(570, 350);
graphics.quadraticCurveTo(600, 0, 480, 100);
graphics.lineTo(330, 120);
graphics.lineTo(410, 200);
graphics.lineTo(210, 300);
graphics.closePath();
graphics.endFill();
```

What do you think? I'm not 100% sure I have the skills to pull it off, but if you like the syntax I could try doing a PR

**Comment by michalochman** [comment]
Thanks for the suggestion @ryanking1809.

I'm not sure that we can do it using your proposed syntax in a way that is not confusing – currently all components are backed by their own instance, here we have one instance representing multiple components.

I also think that updates would be complicated. How would you approach this basic scenario of rectangle with animated dimensions and position?

```jsx
<Graphics>
    <Rect 
        fill={{ color: 0xDE3249 }} 
        x={animatedX} 
        y={animatedY} 
        width={animatedWidth} 
        height={animatedHeight} 
    />
</Graphics>
```

**Comment by ryanking1809** [comment]
Yeah ok, that makes things more complicated. Maybe the original draw method suggested makes more sense then! Thanks for considering :)

**Comment by robclouth** [comment]
https://github.com/react-native-community/react-native-svg

This library has a nice way of doing it.

**Comment by michalochman** [comment]
@robclouth can you point to some example specifically? As far as I know, SVG shapes like rectangles or circles are instances of `<rect>` or `<ellipse>` that each can be backed by single DOM node. This is not the case with just Graphics component.

If one wants to have API similar to `react-native-svg` it's very easy to implement using CustomComponent API from `react-pixi-fiber`, there's even an [example implementation of `<Rectangle />` component](https://github.com/michalochman/react-pixi-fiber#simple-graphics-example) in the main README file.

**Comment by robclouth** [comment]
I was referring to the Path component.

**Comment by michalochman** [comment]
@robclouth path is also represented by DOM node, `<path>` in this case.

**Comment by ryanking1809** [comment]
I've implemented my own version of this. I'm not sure how easy it is to integrate into the library's Graphics component, but it's easy enough to do yourself.
```jsx
const TYPE = "GRAPHICS_V2";
const behavior = {
	customDisplayObject: props => new PIXI.Graphics(),
	customApplyProps: function(instance, oldProps, newProps) {
		const {
			draw: oldDraw,
			...restOld
		} = oldProps;
		const { draw, ...restNew } = newProps;
		instance.clear();
		draw(instance)

		// pass other props to renderer so it can apply them to Graphics instance
		this.applyDisplayObjectProps(restOld, restNew);
	}
};
export const Graphics = CustomPIXIComponent(behavior, TYPE);

<Graphics draw={instance => {
        instance.beginFill(0xde3249);
	instance.drawRect(50, 50, 100, 100);
	instance.endFill();
}} />
```
