### ISSUE TITLE
Interaction Events Looping

### ISSUE THREAD

**Issue by ryanking1809** [michalochman/react-pixi-fiber#144]
Hi, I'm excited to try out `react-pixi-fiber` and have bumped into some issues with the interaction events looping with a rectangle component I created. I'm not sure if it's all `react-pixi-fiber` components or just `CustomPIXIComponent`. 

You can play around with the code sandbox here https://codesandbox.io/embed/react-pixi-fiber-react-spring-b4ett

If you click on the rectangle you notice it constantly is logging `click` - any ideas on what might be causing it?

**Comment by michalochman** [comment]
Hi @ryanking1809, it's because on each `customApplyProps` in your custom component you are calling:
```js
instance.on("pointerup", onClick);
```
but you never call
```js
instance.off("pointerup");
```
to remove previously added event handler.

`customApplyProps` is called every time props are updated which in this case is every time the rectangle is animated.

**Comment by michalochman** [comment]
A quick tip: use `this.applyDisplayObjectProps(oldProps, newProps);` API that is mentioned as a note to [`customApplyProps` ](https://github.com/michalochman/react-pixi-fiber#customapplypropsdisplayobject-oldprops-newprops-optional) description. You should pass all props that you don't use directly in your implementation of `customApplyProps`.

In your example, you could remove `instance.on("pointerup", onClick);` and pass `pointerdown` prop to `Rectangle` and then pass it further down using `applyDisplayObjectProps` call.

**Comment by ryanking1809** [comment]
Ok got it, thanks! Do you have any info on how `applyDisplayObjectProps` works? 
Can I pass it any event?

**Comment by michalochman** [comment]
@ryanking1809 all `applyDisplayObjectProps` does is to handle prop changes the same way non-custom components handle it. For example, if `<Sprite />` component was not provided, it could be implemented using custom component this way:

```js
import { CustomPIXIComponent } from "react-pixi-fiber";
import * as PIXI from "pixi.js";

const Sprite = CustomPIXIComponent({
  customDisplayObject: function() {
    return  new PIXI.Sprite();
  },
  // This is overly verbose jut to illustrate the point.
  // Omitting customApplyProps would result in the same behaviour.
  customApplyProps: function(instance, oldProps, newProps) {
    this.applyDisplayObjectProps(oldProps, newProps)
  }
}, "Sprite");
```

----

`<Rectangle />` custom component example mentioned in README is very basic and incomplete. The actual implementation that would pass other props to the renderer could look like this:
```jsx
// components/Rectangle.js
import { CustomPIXIComponent } from "react-pixi-fiber";
import * as PIXI from "pixi.js";

const TYPE = "Rectangle";
export const behavior = {
  customDisplayObject: props => new PIXI.Graphics(),
  customApplyProps: function(instance, oldProps, newProps) {
    const { fill: oldFill, x: oldX, y: oldY, width: oldWidth, height: oldHeight, ...restOld } = oldProps;
    const { fill, x, y, width, height, ...restNew } = newProps;

    // draw rectangle using x, y, width, height and fill props
    instance.clear();
    instance.beginFill(fill);
    instance.drawRect(x, y, width, height);
    instance.endFill();

    // pass other props to renderer so it can apply them to Graphics instance
    this.applyDisplayObjectProps(restOld, restNew);
  }
};
export default CustomPIXIComponent(behavior, TYPE);
```

**Comment by ryanking1809** [comment]
Oh perfect, thank you!
