### ISSUE TITLE
React's `Context.Providers` defined outside of the <Stage> is not available within it

### ISSUE THREAD

**Issue by RossKinsella** [michalochman/react-pixi-fiber#145]
### Description
https://github.com/michalochman/react-pixi-fiber/pull/127#issuecomment-531547402

### Steps to reproduce

1. Define a context provider outside of the stage
2. Consume it inside of the stage
3. You will see that the consumed context is an empty object

### Additional info
I think we need to write some code here to pass along context
https://github.com/michalochman/react-pixi-fiber/blob/master/src/ReactPixiFiber.js#L206

I'll have a quick look into this and see if I can make a PR

- react-pixi-fiber version: 0.9.2
- React version: 16.9.0
- ReactDOM version: 16.9.0
- PixiJS version: 5.0.4

**Comment by michalochman** [comment]
Hi @RossKinsella, this is react issue, context is not shared between different renderers when you use new context api (it was working with legacy api). See #93 for workarounds.

**Comment by RossKinsella** [comment]
Gotcha @michalochman, thanks for the workaround link!
