### ISSUE TITLE
Stage changed

### ISSUE THREAD

**Issue by J00nz** [michalochman/react-pixi-fiber#146]
### Description

As a developer it would be nice to have better access to the "class" version of "Stage".
In the latest version of react-pixi-fiber the interface of "Stage" changed from "class" based to a be either a "class" or "function" depending if the react-version has support for hooks or not.
This is nice, but it would be great to have convenient access to a specific implementation.
Suggest exporting the "createStageClass" in main index as well.

### Additional info

- react-pixi-fiber version: 0.10.0
- React version: 16.8+ 
- ReactDOM version: 16.8+
- PixiJS version: any

**Comment by michalochman** [comment]
Sure, we can easily do that. Out of curiosity, what would be the use case?

**Comment by J00nz** [comment]
For example, we have added some additional functionality to the stage class, stuff that is relevant for us but might not be so relevant for other use cases, all built on the old class interface. After updating they broke, since we're using the latest react version.
Just exporting the "createStageClass" would enable us to use that and re-add our custom functionality.

**Comment by michalochman** [comment]
If you don’t want to share exact use case, would you be able to show some
abstract example based on what you do to Stage class?

This information will be helpful to understand what are the possible
implications of changes to this library, so maybe we can lock the interface
to prevent such issues in the future.

**Comment by J00nz** [comment]
Well sure, we have a couple of things we've added: 
In the componentDidMount we added the following: 
    const { prepare, prepareCallback } = this.props.options
    
    if (prepare) {
      const { renderer } = _app
      const { plugins } = renderer
      if (!Array.isArray(prepare)) {
        plugins.prepare.upload(prepare, prepareCallback)
      } else {
        prepare.forEach((item) => {
          plugins.prepare.add(item)
        })
        plugins.prepare.upload(prepareCallback)
      }
    }

This makes it so that we can send the textures that we want to prepare directly to the GPU
We have more mundane stuff as well, like: 

  ___checkprops(props, oldProps) {
    if (props.paused !== oldProps.paused) {
      if (props.paused) {
        PIXI.ticker.shared.remove(this._app.render, this._app)
      } else {
        PIXI.ticker.shared.add(this._app.render, this._app)
      }
    }
  }

  componentWillReceiveProps(nextProps) {
    this.___checkprops(nextProps, this.props)
  }

Which makes it so that the game stops rendering if we pause the game.

**Comment by J00nz** [comment]
So basically we just add a bit of custom functionality on top of the existing stage :)

**Comment by michalochman** [comment]
@J00nz check out `0.11.0`

**Comment by J00nz** [comment]
Awesome, looks great! 👍
