### ISSUE TITLE
Version of PIXI in peer dependencies not correctly supported in Typescript definition

### ISSUE THREAD

**Issue by Othreumaru** [michalochman/react-pixi-fiber#150]
### Description
Hello, thanks for making this great library, I really enjoy using it.

I found small issue with your types, you define peer dependency as `"pixi.js": "^4.4.0 || ^5.0.0"`

Now in PIXI 5.0 they removed the PIXI.extras namespace and all members were moved into PIXI namespace as you can see in this code snippet copied from their git repo:

`
    /**
     * This namespace has been removed. All classes previous nested
     * under this namespace have been moved to the top-level `PIXI` object.
     * @namespace PIXI.extras
     * @deprecated since 5.0.0
     */
    PIXI.extras = {};
`

Now in your index.d.ts you define BitmapTextProperties as following:

`
export interface BitmapTextProperties extends ChildlessComponent<PIXI.extras.BitmapText & InteractiveComponent> {
    text: string;
  }
`

This causes a problem during compilation when using PIXI 5 and latest version of react-pixi-fiber

### Steps to reproduce

1. Install PIXI 5.x and react-pixi-fiber 0.11.1
2. Run typescript compilation

### Additional info

- react-pixi-fiber version: 0.11.1
- React version: ^16.11.0
- ReactDOM version: ^16.11.0
- PixiJS version: ^5.2.0

Additionally I can't find version 0.11.1 in your GitHub page released versions.

**Comment by michalochman** [comment]
Hi @Othreumaru, do you have any suggestions for solving this issue?

GitHub releases list is now fixed.

**Comment by Othreumaru** [comment]
You need to decide which version of PIXI you support or in case it's both you need to reflect that in your typescript type definitions.

**Comment by michalochman** [comment]
We support both v4 and v5 of PixiJS. TypeScript definitions were created by contributors and I am just starting to use it so if you know how to fix it then contributions are more than welcome!

**Comment by Othreumaru** [comment]
I was playing with the types a bit to make them work in all your supported versions and I came up with this solution [https://github.com/Othreumaru/react-pixi-fiber/commit/0614079008cc255d90a3c5e8b54ebd5e79dfbbbe#diff-b52768974e6bc0faccb7d4b75b162c99](link)

This works because types in typescript are compared by shape, so I fix it by removing the location reference and redefining the type locally.

If you like this change I can make a PR.

**Comment by michalochman** [comment]
@Othreumaru thanks. Would you be able to share a piece of application code that shows that the current types are not sufficient and that your solution works? I would like to try to explore other possibilities and see that the solution you are proposing would work – what I don't like is that we would need to redefine types that are already declared in PIXI types.

**Comment by kresli** [comment]
I like to add my two cents here. You can't support 2 major version within same repo with d.ts. Thats not possible. you can create 2 repo in @types to support both eg `@types/react-pixi-fiber-4` and `@typescript/react-pixi-fiber-5` I don't like it personally but I don't see other solution here. 
Maybe you could support only latest pixijs and create @types for legacy?

**Comment by michalochman** [comment]
@Othreumaru @kresli I think I have managed to fix types to work with both PixiJS v4 and v5, see #166.
