### ISSUE TITLE
External PIXI.Application in Stage

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#152]
Hi, I like to be able to pass external pixijs app into the stage. eg

```
const app = new PIXI.Application({});
<Stage app={app}/>
```

The reason is I need to keep app accessible by other application's parts and I couldn't find solution yet. Any suggestions?
Thanks

**Comment by michalochman** [comment]
Hi @kresli, I planned to do this eventually, but I have an ongoing refactoring project going and I don't have time to add this myself.

You have at least the following options:
1. Use `render`, see [Without ReactDOM](https://github.com/michalochman/react-pixi-fiber#without-reactdom) section of README.
2. Create containing component, save `ref` to `Stage`, e.g. `<Stage ref={stage => (this.stage = stage)} />`, then access the app in `componentDidMount` via `this.stage._app` (or use `useEffect` hook and access accordingly)) and store it in accessible location.
3. Please submit PR with `createStageClass` and `createStageFunction` updated accordingly 😉

**Comment by kresli** [comment]
Thanks for suggestion and I'm happy to help with this issue.

1. I doing this already, however doesn't work properly. React isn't notified if any sub-child  components change and will not trigger update eg: (<child><subchild={x}/><child>) . Using <Stage/> works perfectly fine because you have `applyUpdate`.  This is quite important because I'm using mobx which need to be notified of changes.
2. I literally storing app outside in another controller which is not aware of any react . React is used  as view only layer so this is NO GO
3. Here is a simple idea (no hooks yet)  https://github.com/kresli/react-pixi-fiber/commits/master 
I apologize for messy commits. Before creating any PR I tried to use it in my local dev but wasn't able to properly link it. So I gave up and tried to ask you here :)

**Comment by michalochman** [comment]
@kresli I have opened a PR #154 which adds `app` prop to `Stage` component. There is an example added which confirms that it works, but would you be able to test it in your app?

**Comment by kresli** [comment]
@michalochman Hi, Thanks a lot for this and sorry for late respond. Currently I'm very busy but I'll try to find a time to test it today. Again, sorry for late respond.

**Comment by michalochman** [comment]
Don't worry @kresli, you can now check it in 0.12.0 version
