### ISSUE TITLE
Pixi.js will drawImage when every frame update

### ISSUE THREAD

**Issue by wss534857356** [michalochman/react-pixi-fiber#155]
### Description
When I tried to draw a list view, I noticed that the number of frames was very low on earlier versions of Android. So I tried to record the performance and found that I was redrawing the image every time. When there were too many images, this would cause a freeze. Are there any solutions or optimization methods to help me with this situation? Has anyone else encountered a similar situation? This is not a problem with RPF, but it feels like most people should have the same problem as me.

### Additional info

- react-pixi-fiber version:  v0.10.0
- React version: v16.9.0
- ReactDOM version: -
- PixiJS version: v5.1.3

![image](https://user-images.githubusercontent.com/13134422/69917572-70538280-14a2-11ea-801d-fead31458ecd.png)

You can see that every pink square means drawImage

**Comment by michalochman** [comment]
Hi @wss534857356, the functions executed are from PIXI, not from RPF. If you don't want to render on every animation frame, you can now provide PIXI.Application via `app` prop to `Stage` component so you can easily configure the [ticker](https://pixijs.download/dev/docs/PIXI.Ticker_.html) on your own.
