### ISSUE TITLE
how to animate rectangle?

### ISSUE THREAD

**Issue by pivcec** [michalochman/react-pixi-fiber#158]
### Description

I have rendered a rectangle inside of Notes component, and I would like to use props.movement in order to animate it from right to left of screen. 

I would also like to know how to add many rectangles to one entity so that I can animate the single entity.

### Steps to reproduce

please see following codesandbox: [link](https://codesandbox.io/s/react-pixi-fiber-demo-rotating-bunny-t5y3f)

### Additional info

- react-pixi-fiber version: 0.8.1
- React version:16.8.6
- ReactDOM version: 16.8.6
- PixiJS version: 4.8.8

**Comment by michalochman** [comment]
@pivcec I replied to your query on [gitter](https://gitter.im/react-pixi-fiber/Lobby).

For sanity, let's keep github issues only for library related ideas, improvements and bugs, not for per-project help – thanks!
