### ISSUE TITLE
100 RotatingBunny components slideshow

### ISSUE THREAD

**Issue by PByH** [michalochman/react-pixi-fiber#161]
Hello!
I'm newbie in react-pixi-fiber, so may be my question is not very kind, but... There are 2 tests, which I made with Rotating bunny demo:
1) If I add 100 RotatingBunny components on one scene, the performance looks not good even on strong machine.
2) If I add 100 Bunny components into RotatingBunny component (each with random rotation prop on Render) the performance is ok.
As far as I can suppose, the reason of performance problem is that there are much more setState calls in first example, and this may cause render calls of parent component. But shouldn't fiber solve that problem with skipping unuseful render calls? Or there is a different problem?

**Comment by michalochman** [comment]
Hi, have a look at both Bunnymark examples in repo, they both handle
thousands of bunnies, the custom one even ten of thousands. If you want to
batch updates then you can also have a look at that example as well.

In general, react-pixi-fiber is only an interface from React to PixiJS, so
all React concepts hold true. To be more specific, there is no such thing
as “skipping unuseful render calls” in React by default, each setState will
launch React’s render cycle.

**Comment by PByH** [comment]
Thanks for the answer!
Sorry for not providing demos in my first message. So here they are:
1) https://codesandbox.io/s/react-pixi-fiber-demo-rotating-bunny-fh092
2) https://codesandbox.io/s/react-pixi-fiber-demo-rotating-bunny-otmt1
I beleive that the performance problem in first demo is not on the react-pixi-fiber side, and may be I should ask my question in React/Fiber repo... 
But the main question for me is: what can I do to avoid performance problems in situation when there are many animated objects in my game, each of which changes its state every frame? Or react architecture means not to place frequently changed props in state? Well, if it is, RotatingBunny component is a bad component, because it changes its state on every frame :)

**Comment by michalochman** [comment]
Bunny example is a trivial one for a reason - it’s just a minimal demo.

Don’t animate using setState as it is slow when there are many components
to render (Animation in react-dom using setState would be equally slow).
You can use react-spring (no example in repo), animated (example in repo)
or create custom components that are animated by Pixi itself (e.g. by
ticker).

**Comment by PByH** [comment]
Thanks for reply! Your answer is very helpful for me :+1:
