### ISSUE TITLE
Canvas Fallback

### ISSUE THREAD

**Issue by snippet-nicotine** [michalochman/react-pixi-fiber#169]
### Description

Hello,

First of all I would like to thanks you for this amazing library, it helps me so much on a professional project.
I need the canvas fallback in case a user doesn't have any hardware acceleration, and I cannot found a way to enable it. It seems to work on clasisical PIXI.js but not on react-pixi-fiber.
Do you know how I can enable it?

### Additional info

- react-pixi-fiber version: 1.0.0-beta.0
- React version: 16.12.0
- ReactDOM version: 16.12.0
- PixiJS version: 5.2.0

**Comment by michalochman** [comment]
Hi @snippet-nicotine, this should work out of the box. I can see in the additional info that you're using PixiJS v5, are you using `pixi.js-legacy` build? Regular build does not have support for canvas renderer, see https://github.com/pixijs/pixi.js/wiki/v5-Migration-Guide#canvas-becomes-legacy

**Comment by snippet-nicotine** [comment]
Yes I'm using the `pixi.js-legacy` build, but I'm not calling the `PIXI.autoDetectRenderer()`, where I am supposed to call this in  `react-pixi-fiber` application?

This is my application entry point:
```JSX
<AppContext.Consumer>   
       {app =>
             <Viewport app={app} >
                    <StoreProvider value={rootStore}>
                        <House/>
                    </StoreProvider>
                 </Viewport>
                }
 </AppContext.Consumer>
```

**Comment by michalochman** [comment]
@snippet-nicotine I do not reproduce, see: https://codesandbox.io/s/react-pixi-fiber-pixijs-v5-renderer-type-tbufe

With WebGL turned on I see:
![image](https://user-images.githubusercontent.com/1628450/74363668-5354fd00-4dcb-11ea-9661-23628c40bcbf.png)


With WebGL turned off I see:
![image](https://user-images.githubusercontent.com/1628450/74363705-6536a000-4dcb-11ea-81fb-4ee890eb931f.png)

**Comment by snippet-nicotine** [comment]
Yes it's definitively something on my side, I may have something wrong in my env.
@michalochman Thank you for taked time with this!

**Comment by snippet-nicotine** [comment]
Ok so I solved the problem by removing node_modules and package-lock.json (i've forgotten this one).
https://github.com/pixijs/pixi.js/issues/6256
So now it works great! Thanks again and sorry for the inconvenience!

**Comment by michalochman** [comment]
No worries, at least now we have this documented in some way 😄
