### ISSUE TITLE
Library Helpers

### ISSUE THREAD

**Issue by jmfirth** [michalochman/react-pixi-fiber#17]
Provide some additional library-level helpers to make working with this library easier.  Previous conversion is in #16.

Examples:

1. Extract `Stage.childContextTypes` for consumer use.
2. A extension of `React.Component` that provides context types ([example](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/src/ReactPixiFiber.js#L318-L319), [tests](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/test/typescript/stagedcomponent.tsx))
3. A method that configures `React.StatelessComponent` with context types ([example](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/src/ReactPixiFiber.js#L322-L326), [tests](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/test/typescript/lift.tsx))
4. A method that maps context to arbitrary properties of any `React.Component` or `React.StatelessComponent` ([example](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/src/ReactPixiFiber.js#L329-L337), [tests](https://github.com/jmfirth/react-pixi-fiber/blob/d1f8e415f33850d7c66ed0a337bd86a42707811d/test/typescript/connect.tsx))

**Comment by jmfirth** [comment]
Once #16 is merged I will submit an isolated PR for #1 in the list above.

**Comment by michalochman** [comment]
Regarding 4, the general use case would be to use `PIXI.Application`'s `ticker` and `loader` (less likely a `screen`, `renderer`, `stage` and `view`) members, so what would you say about creating specialised higher-order components or components with render props named `withTicker()`, `withLoader()`, _etc_., instead of a single `connect` function?

**Comment by 3rd** [comment]
Using `AppContext` breaks ts as well, it's defined as a type.

**Comment by michalochman** [comment]
@3rd thanks, I missed this! I have just fixed it in #166.
