### ISSUE TITLE
Using ReactDOM.createPortal within the react-pixi-fiber render tree

### ISSUE THREAD

**Issue by RossKinsella** [michalochman/react-pixi-fiber#173]
I'd like to use the ReactDOM.createPortal API to render a popup-modal in HTML in a separate tree which has access to some state I have buried in my react-pixi-fiber tree.

When I attempt this, I'm getting invariant exceptions, as I am attempting to render HTML within the react-pixi-fiber tree.

Any ideas on how to eject from that renderer for parts of my render tree?

Thanks

**Comment by RossKinsella** [comment]
I've achieved this by creating another root div in my document which I then render a new React tree to from within the Pixi tree with this helper component:

```
import React from "react";
import ReactDOM from "react-dom";

const EjectPixi = ({
  children
}: {
  children: JSX.Element | JSX.Element[];
}) => {
  ReactDOM.render(
    children,
    document.getElementById("pixi-eject-root")
  );

  return null;
};

export default EjectPixi;
```

**Comment by michalochman** [comment]
Thanks for the solution @RossKinsella.

FYI I'm looking into proper Portal support for Pixi components this month.
