### ISSUE TITLE
no docs on using PIXI.AnimatedSprite

### ISSUE THREAD

**Issue by ldd** [michalochman/react-pixi-fiber#186]
### Description
Currently in the examples, you only have a reference to animating a Sprite using Animated. I was wondering if it was possible to use `PIXI.AnimatedSprite` somehow. I also found [this codepen](https://codesandbox.io/embed/0qkll4y5nw) by another user that uses Spring.

Anyways,  my suggestion is to add docs that explicitly say how animations are expected to work with this package.

- react-pixi-fiber version: 0.14.0
- React version: 16.13.1
- ReactDOM version: 16.13.1
- PixiJS version: 5.2.6

**Comment by michalochman** [comment]
Hi @ldd, you can use [Custom Components](https://github.com/michalochman/react-pixi-fiber#custom-components) for that.

The AnimatedSprite you link is actually PIXI.Sprite, but animated using [react-spring](https://www.react-spring.io/).
