### ISSUE TITLE
Unable to render a stage in a normal React app

### ISSUE THREAD

**Issue by ianjsikes** [michalochman/react-pixi-fiber#191]
Is it possible to use react-pixi-fiber to create a canvas that is used in part of a larger HTML-based React app? For example, I am building a website with React, and I thought I would just put a `<Stage />` component where I want the canvas to appear. In all the examples, the Stage has to be rendered directly into a canvas using `ReactDOM`'s render. If I try to do what I want, I get the error `"ReactPixiFiber did not render into container provided"`

**Comment by michalochman** [comment]
Hi @ianjsikes, not sure why it would not work for you, please see this sandbox as an example:
https://codesandbox.io/s/tender-dream-stf2x

All I did was to render Stage with some objects in the default codesandbox React template.

**Comment by ianjsikes** [comment]
interesting. I can replicate that. the issue must be something else related to my setup. my bad. thanks for the help.
