### ISSUE TITLE
Getting warning from ReactDom

### ISSUE THREAD

**Issue by eric-ploof** [michalochman/react-pixi-fiber#193]
### Description

I get this warning: `Warning: Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.` regardless of what I try.

```
import React from "react";
import { render } from "react-dom";
import { Sprite, Stage } from "react-pixi-fiber";

export default () => (
    render(
        <Stage options={{ backgroundColor: 0x10bb99, height: 600, width: 800 }}>
        </Stage>,
     document.getElementById("container")
    )
);
```

### Steps to reproduce

1. Load page

### Additional info

- react-pixi-fiber version: 0.14.1
- React version: 16.13.1
- ReactDOM version: 16.13.1
- PixiJS version: 5.3.3

**Comment by michalochman** [comment]
@eric-ploof what are you trying to do? This is not how you use `render` method from `react-pixi-fiber`. You should use `render` the same way you would use it from `react-dom`. Or just use `render` from `react-dom` and render `Stage` there. 

Here it looks like you create component that calls `render` (which is a side effect) and does not return anything. Components should not call side effect in render phase and should return something.

Please read [Usage section of README](https://github.com/michalochman/react-pixi-fiber#usage) or inspect available [examples](https://github.com/michalochman/react-pixi-fiber/tree/master/examples).
