### ISSUE TITLE
Question: TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by kafinsalim** [michalochman/react-pixi-fiber#195]
### Description
Hi, Thanks for making this cool library.

I got a warning below:

<img width="805" alt="Screenshot 2020-11-26 at 14 33 32" src="https://user-images.githubusercontent.com/33047308/100320852-63556a80-2ff4-11eb-9c92-a99d2d28751a.png">

I see it is says React DevTools, but if I remove all my `react-pixi-fiber` code the warning disappear. So I assume there is something I do wrong with my `react-pixi-fiber` code

Here is the code:

![Screenshot 2020-11-26 at 14 44 05](https://user-images.githubusercontent.com/33047308/100321827-e3c89b00-2ff5-11eb-9d9f-c93f10ac6133.png)
![Screenshot 2020-11-26 at 14 47 19](https://user-images.githubusercontent.com/33047308/100322220-84b75600-2ff6-11eb-8bc5-79df06efd3a9.png)
![Screenshot 2020-11-26 at 14 50 10](https://user-images.githubusercontent.com/33047308/100322355-b92b1200-2ff6-11eb-9604-3fbda0f8c91b.png)
![Screenshot 2020-11-26 at 14 48 42](https://user-images.githubusercontent.com/33047308/100322228-88e37380-2ff6-11eb-9def-f0a140f810e8.png)

and this is what I'm trying to build, something like an isometric map builder
![image](https://user-images.githubusercontent.com/33047308/100322457-e37ccf80-2ff6-11eb-85e2-6febff6b6419.png)

### Additional info

- react-pixi-fiber version: 0.14.1
- React version: 16.11.0
- ReactDOM version: 16.11.0
- PixiJS version: 5.3.3
- NextJS version: 9.3.6

**Comment by kafinsalim** [comment]
BTW my code works but it just has `TypeError: Invalid value used as weak map key` red warning which I have no idea why

**Comment by michalochman** [comment]
Hi @kafinsalim, weak maps are not used in `react-pixi-fiber` codebase, so not sure what this is about. Are you sure this is not something that comes from your build process or other areas of the app?

Can you try to create a codesandbox with this issue present? You can use this template as a starter: https://codesandbox.io/s/react-pixi-fiber-template-ohk6z

**Comment by kafinsalim** [comment]
I have this https://github.com/kafinsalim/isometric-map-creator,  if you run this locally with `npm run dev` it will have the same warning in the console. I'll try making codesandbox for this if it is not sufficient

**Comment by michalochman** [comment]
@kafinsalim thanks, I had a look and this was an issue with your code and React DevTools.

In `EmptyBlock.js` you are exporting:
```
export default React.memo(Rectangle);
```
which is wrong, you should just export:
```
export default Rectangle;
```
because in this case `Rectangle` returned from `CustomPIXIComponent` is not exactly a React component, it is a string that is later evaluated to your custom component during reconciliation.

The solution here is just not to use `React.memo` on `CustomPIXIComponent`s.
