### ISSUE TITLE
Mask scaling

### ISSUE THREAD

**Issue by GarethChetwood** [michalochman/react-pixi-fiber#199]
Was having an issue with a mask not scaling, stumbled upon this related issue:

https://github.com/pixijs/pixi.js/issues/1978

There they recommend adding the mask to a container with `addChild()`, so it inherits any transforms.

How would we go about doing this kind of thing with react-pixi-fiber?

**Comment by michalochman** [comment]
Hi @GarethChetwood it depends how you mask look. Can you create sandbox using this template: https://codesandbox.io/s/react-pixi-fiber-template-ohk6z?

**Comment by GarethChetwood** [comment]
Alright cheers for that, I had a go and added a rounded rectangle and surrounded both (it and the bunny) with a container, then tried to use a ref as the mask:

https://codesandbox.io/s/competent-gould-5xs54

The shape still shows up though, not behaving as a mask. Have I missed something out?

**Comment by michalochman** [comment]
@GarethChetwood it's because your component does not rerender so the `mask` prop is still `null`. It's better to use callback  ref in this case, for example using `useState` hook, like so: https://codesandbox.io/s/react-pixi-fiber-github-issue199-v6dic :)
