### ISSUE TITLE
Error shows when assigning `sortableChildren ` to Container

### ISSUE THREAD

**Issue by huang-yuwei** [michalochman/react-pixi-fiber#203]
### Description
`Warning: Invalid value for prop 'sortableChildren' on '<Container />'.` error shows when assign the `sortableChildren ` to `Container `

### Steps to reproduce
https://codesandbox.io/s/sortablechildren-error-in-react-pixi-fiber-vw4x5?file=/src/App.js
1. assign the `sortableChildren ` to `Container`

### Additional info

- react-pixi-fiber version: 1.0.0-beta.6
- React version: 17.0.0
- ReactDOM version: 17.0.0
- PixiJS version: 5.3.7

**Comment by michalochman** [comment]
Hi @huang-yuwei, is the warning shown when rendering in StrictMode as per discussion in https://github.com/michalochman/react-pixi-fiber/issues/201#issuecomment-743802381 or is it always shown?

**Comment by huang-yuwei** [comment]
Hi, @michalochman thank you for the quick response.
It seems like it is always shown, so I don't think it is related to the #201.
https://codesandbox.io/s/sortablechildren-error-in-react-pixi-fiber-vw4x5?file=/src/App.js

**Comment by michalochman** [comment]
Ok, looks like I have only disabled one type of warnings when not in strict mode. I will change it to not show any warnings unless rendered in strict mode.

**Comment by huang-yuwei** [comment]
BTW, is there any way that I can find the v1 code in this repository?
Sincerely hope I can contribute to this repository 🙂

**Comment by michalochman** [comment]
v1 is on the `develop` branch

**Comment by michalochman** [comment]
@huang-yuwei check out `react-pixi-fiber@1.0.0-beta.7` – there should be no warning unless you use `React.StrictMode`.

**Comment by huang-yuwei** [comment]
Thank you for fixing it in such a short time🙏
