### ISSUE TITLE
TS 4.2.3 and PIXI.js 6.0.2 throws TS error

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#210]
![image](https://user-images.githubusercontent.com/3826097/116787822-44c13700-aa9e-11eb-9c46-13ebb8bdf228.png)
### Additional info

- react-pixi-fiber version: 0.14.2
- React version: 17.0.2
- ReactDOM version: 17.0.2
- PixiJS version: 6.0.2
- @types/react: 17.0.4

**Comment by kresli** [comment]
seems like all the props are expected as `((event: InteractionEvent) => void) | undefined`

**Comment by kresli** [comment]
here is the line causing the issue
https://github.com/michalochman/react-pixi-fiber/blob/fcf4fddab981c5eabf623697325ab579b34cad52/index.d.ts#L107

**Comment by michalochman** [comment]
Hi @kresli, thanks for reporting. The purpose of this type is to support props like `pointerdown` or `mouseup`, etc. when display object has `interactive` set to `true`, see [ClickExample/index.js](https://github.com/michalochman/react-pixi-fiber/blob/fcf4fddab981c5eabf623697325ab579b34cad52/examples/src/ClickExample/index.js).

Do you know the last version of TypeScript and PixiJS that worked correctly for you?

**Comment by michalochman** [comment]
I have narrowed down the issue to `InteractionEventTypes` being removed in PixiJS v6. We will either need to hardcode the list of events to work as props or find another way to support them.

**Comment by michalochman** [comment]
@kresli I fixed it in `react-pixi-fiber@1.0.0-beta.9`

**Comment by kresli** [comment]
I can confirm it has been fixed in beta.9

Thank you

**Comment by michalochman** [comment]
`react-pixi-fiber@1.0.0` released.
