### ISSUE TITLE
Providing app for <Stage> doesn't create canvas

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#211]
Following will not create a new canvas that should be added to a parent component. Is there some workaround for it?

```typescript
import {FunctionComponent, useRef} from 'react';
import {Stage} from 'react-pixi-fiber';
import * as PIXI from 'pixi.js';

export const App: FunctionComponent = ({ children }) => {
  const app = useRef(new PIXI.Application());
  return <Stage app={app.current}>{children}</Stage>
};
```
and rendered tree looks like 
```html
<div class="canvasParent">
 <!-- missing canvas --> 
</div>
```
- react-pixi-fiber version: 0.14.2 & 1.0.0-beta.9
- React version: 17.0.2
- ReactDOM version: 17.0.2
- PixiJS version: 6.0.2
- @types/react: 17.0.4

**Comment by michalochman** [comment]
Hi @kresli, this is intended behaviour.

When you provide `app` via prop, you are expected to place the canvas in the DOM yourself. One of the reasons is that you can pass `view` to `PIXI.Application` options, which may be canvas already existing somewhere in the DOM. `react-pixi-fiber` has no way knowing whether you want to move it to new parent or not, so the decision is left to the user.

There are multiple ways to do it, for example you can return some wrapper `div` from your `App` component, assign `ref` to it and append canvas in `useEffect` or `useLayoutEffect`.
