### ISSUE TITLE
`prop-types` is not specified in dependencies

### ISSUE THREAD

**Issue by BasixKOR** [michalochman/react-pixi-fiber#221]
### Description
This library uses `prop-types` in its source code without listing it as dependencies, which breaks Yarn PnP and generally discouraged.

### Steps to reproduce

1. Enable Yarn PnP
2. `yarn add react react-dom react-pixi-fiber pixi.js`
3. try to render `<Stage />`

### Additional info

- react-pixi-fiber version: 0.14.2
- React version: 17.0.0
- ReactDOM version: 17.0.0
- PixiJS version: 6.0.4

**Comment by michalochman** [comment]
Hello @BasixKOR, thanks for reporting. Is `prop-types` the only offending library or are there more to be listed as dependencies?

**Comment by BasixKOR** [comment]
It seems like there's no unlisted dependencies other than prop-types. Do we need it though?

**Comment by michalochman** [comment]
Yes, `prop-types` are used to validate `Stage` props.

I will add them to dependency list.

**Comment by michalochman** [comment]
Fixed in `react-pixi-fiber@0.14.3`.
