### ISSUE TITLE
Invalid type of ref of Stage

### ISSUE THREAD

**Issue by michalochman** [michalochman/react-pixi-fiber#225]
### Description

> Hey @michalochman I am having an issue with `1.0.0-beta.10`. In my project I use `createStageClass` and when I render `<Stage />` I am providing a ref function. (For example `<Stage ref={(stage) => { /* do stuff */ }} />`
What I'm actually doing in the ref function is store a reference to the `stage._app` so I can use it in other contexts like automated tests. This has been working well for me in the stable versions. However, I notice that now, I need to do `stage._app.current` to get to the actual application object now. However, the typings don't seem consistent with that change, for example, I don't see a mention of `current` here: https://github.com/michalochman/react-pixi-fiber/blob/8a9ff332af6795be4dcfc82c8914641eaedc6748/index.d.ts#L214
I'm not sure I'm understanding everything, but it looks like the typings may need to be updated?
>
> – https://gitter.im/react-pixi-fiber/Lobby?at=60d154cf9cf3171730e984b5

### Additional info

- react-pixi-fiber version: 1.0.0-beta.10
- sandbox: https://codesandbox.io/s/react-pixi-fiber-github-issue225-czqzo

**Comment by zenblender** [comment]
Thanks @michalochman here's a little more context:

I'm "saving" an instance of the pixi App (pulled from the Stage object) so I can use it in other contexts like Cypress tests. I'm doing this by setting a property on `window`. This is basically what I have working in earlier versions of `react-pixi-fiber`:

```
const Stage = createStageClass()

export const MyStage: FC = () => {
  const stageRef = useCallback((stage) => {
    if (stage) {
      // mounting, "save" instance
      window.pixiApp = stage._app
    } else {
      // unmounting, remove instance
      delete window.pixiApp
    }
  }, [])

  return <Stage ref={stageRef}>{/* stage contents here... */}</Stage>
}
```

**Comment by michalochman** [comment]
@zenblender can you check if this fixes your issue?

https://codesandbox.io/s/react-pixi-fiber-github-issue225-9s6sl?file=/src/App.tsx

**Comment by zenblender** [comment]
Thanks @michalochman !

I've been experimenting with this and it does seem to be helping. My project now runs with this version of `react-pixi-fiber` and latest `@types/react` and `@types/react-dom` after making adjustments to how I reference the `PIXI.Application` object. I am a little confused about the use of a `RefObject` here. I am used to the argument to a ref function always existing, where its `current` property may be set or `null`.

With this version, the `StageRef` argument itself may not exist, so I may need to check multiple things, for example:
```
const currentApp = stageRef?._app.current
if (currentApp) {
  // app is mounting
} else {
  // app is unmounting
}
```

Not a big deal, it just tripped me up as it isn't the pattern I am used to seeing.

Thanks for your help!

**Comment by zenblender** [comment]
Maybe a related question:
Should I be using `StageRef` as the type for the argument to my ref function, or would `StageRef | null` be more correct?

**Comment by michalochman** [comment]
@zenblender try `typeof Stage`

**Comment by michalochman** [comment]
> With this version, the `StageRef` argument itself may not exist, so I may need to check multiple things, for example:

That's how `ref`s work – if you didn't initialise it with value when using [`useRef`](https://reactjs.org/docs/hooks-reference.html#useref) then you always need to check if `ref.current` is set.

**Comment by zenblender** [comment]
That makes sense, regarding `.current`.

Minor point to clarify, if I use `typeof Stage` in the ref function declaration, this seems to imply that `stage` will always be set, but on unmount, it will be `null`. Would it be better to use `typeof Stage | null` so I would be forced to (properly) use the `?` optional chaining?

For example:

```
const Stage = createStageClass()

export const MyStage: FC = () => {
  const stageRefFn = useCallback((stage: typeof Stage | null) => {
    const currentApp = stage?._app.current // I must use '?' here which seems safer
    if (currentApp) {
      // mounting
    } else {
      // unmounting
    }
  }, [])

  return <Stage ref={stageRefFn}>{/* stage contents here... */}</Stage>
}
```

Thanks!

**Comment by michalochman** [comment]
Yes, I think you're right that it's better to use `typeof Stage | null` to factor for such scenari.
