### ISSUE TITLE
usePixiApp seems to now return null

### ISSUE THREAD

**Issue by zenblender** [michalochman/react-pixi-fiber#227]
### Description

The `usePixiApp` hook typings imply that a `PIXI.Application` is always returned, but I'm seeing that with 1.0.0 beta, `null` is sometimes returned, so it seems that at least the typings need updating.

A typical use case for me is to use this hook to get a reference to the app instance, which I then use to manage animation functions. However, I notice this isn't working as it used to.

Here is a codesandbox showing a pattern I have been using: https://codesandbox.io/s/sleepy-rain-sjb0o?file=/src/reactPixiFiberStage.tsx

First it has trouble with the `app.ticker` dependency in the `useEffect` hook.

If I change this to `app?.ticker` then it will run, but may throw errors when trying to reference `.ticker`. It seems I can make progress by using optional chaining in this case, but because `app` is `null` at initial render for some reason, the animation function never runs, so I don't know if it is an issue with `usePixiApp` or maybe something else.

Typically I do this pattern "inside" the `react-pixi-fiber` component tree, where I expect `usePixiApp` to always give me a usable `app` instance, but am running into this problem there as well.

Thanks!

### Additional info

- react-pixi-fiber version: https://pkg.csb.dev/michalochman/react-pixi-fiber/commit/6865cfdd/react-pixi-fiber

**Comment by michalochman** [comment]
Thanks for the report @zenblender, I'll have a look. I want to keep the changes needed to upgrade to the minimum.

**Comment by michalochman** [comment]
@zenblender looking at your example you are not using `usePixiApp` correctly – you can only call it in components that are children of `Stage`, yet you call it in component that renders `Stage`.

**Comment by michalochman** [comment]
I've updated your sandbox: https://codesandbox.io/s/pedantic-albattani-4yz2i?file=/src/canvasBackground.tsx.

It is working correctly, so I will close this issue.

**Comment by zenblender** [comment]
Thanks @michalochman !
I have been trying to upgrade to the 1.0.0 beta on my larger project, and discovered places inside `Stage` where `app` was `null` when returned from `usePixiApp()`. It appeared as though something had changed between these versions, as some animations worked fine while others stopped. I'm going to try to nail down that specific scenario and show that to you if it seems there are other issues. Sorry my example wasn't correct, though I was trying to demonstrate that the typings indicate that `PIXI.Application` is always returned, but sometimes it can be `null`. If the user is doing things improperly, it might be more useful to `throw` a clearer error, or add `| null` to the typings. Thanks for considering :)

**Comment by michalochman** [comment]
@zenblender you are most certainly welcome to create sandbox with an example of this not working – if this indeed happens I will be easily able to reproduce it and fix.

**Comment by michalochman** [comment]
> If the user is doing things improperly, it might be more useful to `throw` a clearer error, or add `| null` to the typings. Thanks for considering :)

I think you may have a point in throwing an error in such scenario, I'll see if this can be done.

However I will not be considering adding `| null` to the typings unless we can demonstrate it is really what is happening. I think it would be an unnecessary penalty for everyone using this hook correctly, i.e. in descendants of `Stage`.

**Comment by zenblender** [comment]
I agree, throwing an error seems best. I think this is a very minor thing, but might save someone from some confusion.

**Comment by michalochman** [comment]
@zenblender starting from `react-pixi-fiber@1.0.0-beta.12`, `usePixiApp` will throw an error when used outside of `<Stage />`.
