### ISSUE TITLE
Performance comparison with react-pixi?

### ISSUE THREAD

**Issue by qpwo** [michalochman/react-pixi-fiber#239]
I searched the repo and google and could not find performance comparisons between react-pixi and react-pixi-fiber. Know of any? (Also could not find any other kind of comparison or explanation of differences.)

**Comment by michalochman** [comment]
@qpwo I don't know about that, but if you want to see what performance is possible to achieve with `react-pixi-fiber`, you will find various Bunnymark examples in this repo:
* https://github.com/michalochman/react-pixi-fiber/blob/0c70c8b5c7a6701e3db07165e4b98957fd5a8507/examples/src/BunnymarkExample/index.js
* https://github.com/michalochman/react-pixi-fiber/blob/0c70c8b5c7a6701e3db07165e4b98957fd5a8507/examples/src/CustomBunnymarkExample/index.js

Anyway, I don't think that there will be any major differences, it's mostly how you write your code that will affect performance the most.
