### ISSUE TITLE
NPM installation of library react-pixi-fiber@beta@1.0.0-beta.5 throws error

### ISSUE THREAD

**Issue by Siva-at-OFS** [michalochman/react-pixi-fiber#241]
### Description

![image](https://user-images.githubusercontent.com/84328892/144795426-5cf7c191-0e18-439c-aea2-54486f8d0b8f.png)

It does work on addition of '--legacy-peer-deps'.

But any suggestion to avoid such initial error is highly appreciated.

### Steps to reproduce

1. (If you haven't already) Just upgrade the react version to 17.0.0, 
2. Try to import react-pixi-fiber@beta@1.0.0-beta.5

> Apart from the steps above, please provide a link to minimal scenario to reproduce the issue using e.g. [code sandbox](http://codesandbox.io/).<br>
> For convenience we have created a [JavaScript template](https://codesandbox.io/s/react-pixi-fiber-template-ohk6z) or [TypeScript template](https://codesandbox.io/s/react-pixi-fiber-typescript-template-613ly) you can use.

### Additional info

- react-pixi-fiber version: beta@1.0.0-beta.5
- React version: ^17.0.0
- ReactDOM version: ^17.0.2
- PixiJS version: ^6.2.0

**Comment by michalochman** [comment]
Thanks for the report @Siva-at-OFS, you are right, the react peer dependencies are incorrectly listed, it should also cover versions 17 and higher. I will fix that.

**Comment by michalochman** [comment]
Actually, `react-pixi-fiber@beta@1.0.0-beta.13`, which is the latest one already lists:

```json
{
   "peerDependencies": {
     "pixi.js": "^4.4.0 || ^5.0.0 || ^6.0.0",
     "prop-types": "^15.7.2",
     "react": "^17.0.0",
     "react-dom": "^17.0.0"
   },
}
```

**Comment by Siva-at-OFS** [comment]
Thanks for quick response @michalochman . 

Is react-pixi-fiber@beta@1.0.0-beta.13 stable version? I saw in your comments that beta.5 is stable.

**Comment by michalochman** [comment]
Yes, it is. We started stress testing it on production in a large app on Friday and so far no issues. We plan release it as officially stable soon, we just need to prepare release notes about breaking changes for people using advanced features.
