### ISSUE TITLE
1.0.0-beta.13 missing index.es.js

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#245]
I have trouble to use the package with `ViteJS` as `index.es.js` is missing 
![image](https://user-images.githubusercontent.com/3826097/148465077-a5087592-4aaa-4485-96ff-e23d46268ae9.png)

**Comment by michalochman** [comment]
Hi @kresli, right – it's missing in the `files` section. I'll add it and release new version.

**Comment by michalochman** [comment]
@kresli I have just released `react-pixi-fiber@1.0.0-beta.14`.

**Comment by cmfcmf** [comment]
I think you also need the `es/` folder to `files` - while the `index.es.js` now exists, it references files in the `es` folder that don't exist.

**Comment by michalochman** [comment]
Nice catch @cmfcmf, whoops! 🤦‍♂️

Fixed in `react-pixi-fiber@1.0.0-beta.15`

**Comment by kresli** [comment]
That fixed it but I'm unsure if thats is enough as 
![image](https://user-images.githubusercontent.com/3826097/150213311-5eff59b0-1c83-4ac7-a5cd-8a0ae289a641.png)
My wild guess `extras` `particles` and `mesh` are plugins and they are not registered.

**Comment by michalochman** [comment]
These are from PixiJS v4 and they are conditionally used. See how an instance of [`BitmapText`](https://github.com/michalochman/react-pixi-fiber/blob/9ba177c7148ad8f5e5de0560901f8f04df2230fd/src/ReactPixiFiberComponent.js#L22-L25) is created for example.

Do you have any ideas how to fix it?

On one hand would prefer not to break compatibility with PixiJS v4, but on the other hand it is already 2 major versions behind and removing it would simplify some areas of the codebase.

**Comment by kresli** [comment]
Could be those dynamically imported like import("mesh")? Just guessing here as I never did that

**Comment by kresli** [comment]
do we really need to import them? As developer could install them as perDependency if necessary

**Comment by michalochman** [comment]
They are not imported per se, what is imported in source coude is: `import * as PIXI from "pixi.js";`.

Perhaps it is the bundler (rollup) that changes the import for the `es` output format. I don't know how to fix it.

**Comment by kresli** [comment]
For now, I'm using `patch-package` on removed imports.

**Comment by michalochman** [comment]
@kresli can you share more details please?

**Comment by kresli** [comment]
sorry for late replay.
I'm using https://www.npmjs.com/package/patch-package and manually remove those imports from `react-pixi-fiber` file in node_modules.
