### ISSUE TITLE
Stage is not compatible with the React's StrictMode

### ISSUE THREAD

**Issue by kresli** [michalochman/react-pixi-fiber#285]
### Steps to reproduce

1. Wrap `<App/>` with `<React.StrictMode> in your examples

### Additional info

- react-pixi-fiber version: 1.0.2
- React version: 18.2.0
- ReactDOM version: 18.2.0
- PixiJS version: 6.5.3

Using StrictMode is a good practice but not necessary. However, a warning not to use strict mode in docs would be handy.

**Comment by michalochman** [comment]
Thanks @kresli, it worked in React 17, so I guess something has changed in the reconciler with regards to `StrictMode`. Leaving this open until we develop resolution for compatibility issues between different React and PixiJS versions.

**Comment by lekzd** [comment]
getting an error with <React.StrictMode> wrapper:

prevProps here in undefined
https://github.com/michalochman/react-pixi-fiber/blob/master/src/Stage/hooks.js#L82 

react-pixi-fiber: 1.0.2

**Comment by michalochman** [comment]
Thanks @lekzd for pointing where the issue is, I will have a look at that.

**Comment by michalochman** [comment]
Hi @kresli and @lekzd, I've included a fix in #291. You can verify using the CodeSandbox links in the PR comment. I would be grateful if you could verify using a scenario that is not one of this repo examples.

**Comment by michalochman** [comment]
Fixed in `react-pixi-fiber@1.0.4`.
