### ISSUE TITLE
Issue on running demo

### ISSUE THREAD

**Issue by raika-dev** [michalochman/react-pixi-fiber#319]
### Description
While running demo example on my pc, I collapsed with these errors

`
Attempted import error: 'extras' is not exported from 'pixi.js' (imported as 'PIXI').
ERROR in ./node_modules/react-pixi-fiber/es/react-pixi-fiber.development.js 17929:23-45
export 'extras' (imported as 'PIXI') was not found in 'pixi.js' (possible exports: ALPHA_MODES, AbstractBatchRenderer, AbstractMultiResource, AbstractRenderer, ... ... ...

ERROR in ./node_modules/react-pixi-fiber/es/react-pixi-fiber.development.js 17942:23-47
export 'mesh' (imported as 'PIXI') was not found in 'pixi.js' (possible exports: ALPHA_MODES, ... ... ...

ERROR in ./node_modules/react-pixi-fiber/es/react-pixi-fiber.development.js 17949:23-55
export 'particles' (imported as 'PIXI') was not found in 'pixi.js' (possible exports: ALPHA_MODES, ... ... ...

ERROR in ./node_modules/react-pixi-fiber/es/react-pixi-fiber.development.js 17962:23-47
export 'extras' (imported as 'PIXI') was not found in 'pixi.js' (possible exports: ALPHA_MODES ... ... ...
`

### Additional info

- react-pixi-fiber version: "1.0.1"
- React version: "^18.2.0"
- ReactDOM version: "^18.2.0"
- PixiJS version: "6.5.1",

**Comment by michalochman** [comment]
Hi, please see discussion in #279
