### ISSUE TITLE
Can't use with new versions of PixiJS

### ISSUE THREAD

**Issue by snatvb** [michalochman/react-pixi-fiber#322]
### Description
Can't use with new versions of PixiJS

`Attempted import error: 'extras' is not exported from 'pixi.js' (imported as 'e').`

### Steps to reproduce

1. Install actual version of PixiJS
2. Build application

### Additional info

- react-pixi-fiber version: 1.0.6
- React version: 18.2.0
- ReactDOM version: 18.2.0
- PixiJS version: 7.2.4

**Comment by michalochman** [comment]
Hi, please see discussion in #279

**Comment by michalochman** [comment]
BTW unless you are using `react-pixi-fiber` already, you might want to use [pixijs/pixi-react](https://github.com/pixijs/pixi-react) instead.

**Comment by snatvb** [comment]
@michalochman I use

**Comment by snatvb** [comment]
> BTW unless you are using `react-pixi-fiber` already, you might want to use [pixijs/pixi-react](https://github.com/pixijs/pixi-react) instead.

Will you support your version or is it better to migrate to [pixijs/pixi-react](https://github.com/pixijs/pixi-react)?

**Comment by michalochman** [comment]
@snatvb, the long-term plan is to migrate to [pixijs/pixi-react](https://github.com/pixijs/pixi-react). If you intend to use PixiJS v7+ with React 18+ then this is the way to go.

We want to port some bug fixes there and also add missing functionalities from this repo.
Until then, I support this repository with bug fixes. I don't plan to implement any new functionalities.

**Comment by snatvb** [comment]
@michalochman thank you for your work. I've migrated. ❤️
