### ISSUE TITLE
Performance Issues Using setState to Create Drag/Pan?

### ISSUE THREAD

**Issue by saricden** [michalochman/react-pixi-fiber#42]
### Description
Is there a performant way to create a drag/pan function using React + Pixi + react-pixi-fiber?

My process is as follows:
1. Bind Stage's onMove, onStart/Down, and onEnd/Up events to my corresponding pan functions. Inside the Stage is a single Collection whose x and y are bound to the component's state.
2. The corresponding pan functions start and stop panning, and set the state's x and y to the event's clientX and clientY properties (and in turn the collection's x and y) on every move event.

The resulting pan is a bit slow/choppy on desktop, but really slow and choppy on mobile.

I tried implementing the same thing using PIXI directly and without using my React component's state, and performance was waay smoother.

However I think the react-pixi-fiber declarative component approach to writing Pixi apps is waay nicer and waay easier to read.

I think the problem is I'm thrashing setState in my onMove functions, and it's getting bogged down.
This performance issue seems like it could be a big problem for many applications though, as most Pixi apps need to modify positions and other properties in realtime (moving characters in games, etc.).

**Does anyone know of a performant way to update Sprite/Collection properties in realtime? (Probably without using React's state)**

I'm worried that defeats the purpose of declaring your Pixi Stage in a component-based way, but hopefully there'll be a solution to this.

### Additional info

- react-pixi-fiber version: 0.4.0
- React version: 16.0.0
- ReactDOM version: 16.0.0
- PixiJS version: 4.7.1

**Comment by michalochman** [comment]
Hey @saricden, unfortunately that's the slowness of `setState`. 

However, this should be easy to implement panning using [davidfig/viewport](davidfig/viewport) and hooking into [Custom Components API](https://github.com/michalochman/react-pixi-fiber#custom-components).

Additionally, you can take a look at #22 which was an attempt to introduce viewport before Custom Components API was added to `react-pixi-fiber`.

**Comment by nervestaple** [comment]
a pattern I've been using with some success is using the ticker to semi-synchronize / throttle state updates -- tracking the elapsed time in state and using sCU to only render every 16ms

**Comment by fbove** [comment]
Hi @michalochman, is there any example integrating pixi-viewport with react-pixi-fiber in component mode (With ReactDOM). I'm on need of dragging and zooming, and that library seems pretty nice.
Hoooking it using Custom Component API is the solution?

Any advice/example would be appreciated.

**Comment by michalochman** [comment]
Hey @fbove, yes you just need to create Custom Component. We have [2 examples](https://github.com/michalochman/react-pixi-fiber/tree/13284e2aae3205f83b511aa449b4d9133f72daf3/examples/src/CustomPIXIComponentExample) available, one with `PIXI.Graphics` and one usage with children.

I originally planned to add pixi-viewport to examples but never really had time to do it.

**Comment by matthieu-foucault** [comment]
FYI, using `pixi-viewport` is as simple as 

```js
import { CustomPIXIComponent } from 'react-pixi-fiber';
import Viewport from 'pixi-viewport';

const TYPE = 'Viewport';
const behavior = {
  customDisplayObject: props => {
    return new Viewport({
      screenWidth: props.app.renderer.width,
      screenHeight: props.app.renderer.height,
      worldWidth: 1000,
      worldHeight: 1000,
      interaction: props.app.renderer.plugins.interaction,
    }).drag()
      .pinch()
      .wheel()
      .decelerate();
  },
};

export default CustomPIXIComponent(behavior, TYPE);
```

and then use with: 

```tsx
      <Stage
        width={STAGE_WIDTH}
        height={STAGE_HEIGHT}
        options={STAGE_OPTIONS}
      >
        <AppContext.Consumer>
          {app =>
            <Viewport app={app}>
              {/* add display objects here */}
            </Viewport>
          }
        </AppContext.Consumer>
      </Stage>
```

I can make a PR to add it to the examples if you want

**Comment by michalochman** [comment]
@matthieu-foucault that would be great!
