### ISSUE TITLE
Context provider in render method throws element is invalid

### ISSUE THREAD

**Issue by Fabiantjoeaon** [michalochman/react-pixi-fiber#52]
### Description
Passing React's new Context API Provider to the react-pixi-fiber render method throws:

_Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object._

### Steps to reproduce

I've decided to make use of React's new context API to pass the props of my stage around easily. This seemed most appropiate for me top-level, which is where my render method from react-pixi-fiber lives. Whenever I pass my context provider as the first argument with children, it throws the error above.

```
        render(
            (
                <StageContext.Provider value={this.stageContext}>
                    <Card
                        timeline={this.cardTimeline}
                        data={this.props.data}
                        reliveIcon={this.props.reliveIcon}
                        stageContext={this.stageContext}
                    />
                </StageContext.Provider>
            ) as any,
            this.stage
        );
```

(Just passing my Card component works however)

Note:
- I have checked and updated react, react-dom and pixi to the latest versions
- I have checked my default and named exports, nothing wrong there

Thanks in advance!

### Additional info

- react-pixi-fiber version: "^0.4.4"
- React version: "^16.3.2"
- ReactDOM version: "^16.3.2"
- PixiJS version: "^4.7.3"

**Comment by michalochman** [comment]
Hey @Fabiantjoeaon, thanks for reporting this. I've updated `react-reconciler` to the latest version and it should work now with `react-pixi-fiber@0.4.5`.

**Comment by Fabiantjoeaon** [comment]
Thanks for getting back and fixing this so quick :) 
However, when I now install `react-pixi-fiber@0.4.5` I get a new error. I'll create a new issue.
