### ISSUE TITLE
Building react-pixi-fiber@0.4.5 with TypeScript throws error

### ISSUE THREAD

**Issue by Fabiantjoeaon** [michalochman/react-pixi-fiber#54]
### Description
When building react-pixi-fiber with typescript there is an error in the type declarations:

`Failed to compile.

/Applications/MAMP/htdocs/relive/skyhawk-cards/node_modules/react-pixi-fiber/index.d.ts
(154,19): Cannot redeclare block-scoped variable 'CustomPIXIComponent'.`

### Steps to reproduce

I'm building with TS with the following config:

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "removeComments": false,
        "outDir": "build",
        "noImplicitAny": true,
        "alwaysStrict": true,
        "strictNullChecks": true,
        "noUnusedLocals": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true,
        "allowSyntheticDefaultImports": true,
        "moduleResolution": "node",
        "baseUrl": ".",
        "jsx": "react",
        "declaration": true,
        "allowJs": false
    },
    "compileOnSave": true
}
```

### Additional info

react-pixi-fiber version: "0.4.5"
React version: "^16.3.2"
ReactDOM version: "^16.3.2"
PixiJS version: "^4.7.3"

**Comment by michalochman** [comment]
Looks like there’s an issue with TypeScript definitions which I did not
write myself. Are you using typescript? I’m not using these myself and I
was able to install 0.4.5 without any issues. I’ll investigate though.

**Comment by Fabiantjoeaon** [comment]
Ahh okay, yes I'm using TypeScript, the error happens in the build process which happens right after installing, should have mentioned.

Thanks, I'll also have a look myself

**Comment by michalochman** [comment]
It would be great if you could fix it and submit PR :)

**Comment by Fabiantjoeaon** [comment]
All right, I did some research and made a PR.

When adding the CustomPIXIComponent typing under its own namespace, it fixes the issue, and my code runs without having issues regarding importing CustomPIXIComponent. I based it on this SO question:
https://stackoverflow.com/questions/40900791/cannot-redeclare-block-scoped-variable-in-unrelated-files/41975448

This is my first PR, so please tell me if I'm doing something wrong.
