### ISSUE TITLE
Async rendering

### ISSUE THREAD

**Issue by JonDum** [michalochman/react-pixi-fiber#62]
Hey @michalochman!

First off, I'd just like to give a huge thanks for this library. I had originally been using `@inlet/react-pixi` and the performance was so bad that it'd not only crash Chrome but sometimes my entire computer.

I switched to your library which only took a few minutes and I instantly had 60fps buttery smooth goodness. So massive props!

Anyways, my use case is rendering large amounts of data for a visualization. The key feature is starting with a narrow viewport and then scaling the container to see lots of the data at once.

Once all the data has been rendered, the pan/zoom animation is very responsive and smooth. However, the initial render of 10,000+ graphics and sprites can take a while. 

I know react fiber has some async rendering in the works. Have you looked into that at all for your customer pixi renderer? Would it be possible to expose or create some sort of API where I could "chunk" the rendering of my items by passing the renderer a subset of things to render per js frame/render call?

**Comment by michalochman** [comment]
Hey @JonDum, thanks for your kind words.

I have not yet looked into async rendering (I guess you mean changes introduced in React 16.3+), but my advice for now would be to try to run the initial render in batches instead of rendering all your objects at once. 

The other thing is that (from my experience) unless you are preloading the sprites to GPU memory, loading them there on render takes a considerable chunk of time the first render takes to complete.

I will leave this issue open until I'm able to explore React async rendering topic with PixiJS.

**Comment by JonDum** [comment]
> The other thing is that (from my experience) unless you are preloading the sprites to GPU memory, loading them there on render takes a considerable chunk of time the first render takes to complete.

Interesting. I'm only using `<Graphics/>` and `<Text/>` objects right now though. However, I think I remember reading that PIXI.Text uses sprites? I wonder if there's a way to batch those with react-pixi-fiber 🤔 

> my advice for now would be to try to run the initial render in batches instead of rendering all your objects at once.

Do you think that will actually improve the final render time though? Wouldn't the final render (with all objects instead of only a few) take the same time as it would have doing it all once the first time?

**Comment by michalochman** [comment]
It would probably take longer, but since you’re starting with a narrow
viewport then there’s probably no reason to immediately render all data
points as only a subset is visible in the initial view. I’d first render
data points that are visible in the viewport, then the rest.
