### ISSUE TITLE
Feature Request: Spine support.

### ISSUE THREAD

**Issue by rockmandash** [michalochman/react-pixi-fiber#63]
First of all, thank you for this wonderful library.
I never write WebGL so declarative.
I was wondering if you can help to add spine support.
This is the library: https://github.com/pixijs/pixi-spine
```javascript
<Spine src={pathToSpineJson} />
```
Something looks like this will be great, thank you!

**Comment by michalochman** [comment]
Hi @rockmandash, you can add Spine support yourself using [Custom Components API](https://github.com/michalochman/react-pixi-fiber#custom-components).

**Comment by rockmandash** [comment]
@michalochman Thank you!
