### ISSUE TITLE
Ability to draw on canvas only when needed (no rAF ticker)

### ISSUE THREAD

**Issue by slorber** [michalochman/react-pixi-fiber#68]
Hi,

Currently, if I have a stage that does not change over time, the Pixi.Application will create a ticker and re-render the stage on every frame. I think it does not make much sense and that we should only re-render when the react component re-render, so that using a PureComponent stage would help prevent re-rendering a stage that does not change.

[More infos here:](http://www.html5gamedevs.com/topic/39347-optimizing-a-pixi-stage/)

This is what I see, when profiling and doing nothing at all in my browser:

![image](https://user-images.githubusercontent.com/749374/44089759-41d9aea2-9fc8-11e8-942a-8de8a008158b.png)

I think in such case the browser should not do any work

**Comment by michalochman** [comment]
Hi @slorber, thanks for reporting however this is intended behaviour by default, you are only considering the most basic case. Please see discussion in #48 which also shows some examples.

**Comment by slorber** [comment]
Thanks @michalochman 

I've found a workaround anyway

```js
class OptimizedStage extends React.PureComponent {
  componentDidMount() {
    this.renderStage();
  }
  componentDidUpdate() {
    this.renderStage();
  }
  renderStage = () => this.application.render();
  render() {
    return (
      <Stage
        {...this.props}
        options={{
          ...this.props.options,
          autoStart: false,
        }}
        ref={ref => {
          if ( ref ) {
            this.application = ref._app;
          }
          else {
            this.application = null;
          }
        }}
      />
    )
  }
}
```

Didn't think of using the context to get access to the app, that would probably be more convenient that my current code based on refs

**Comment by michalochman** [comment]
FYI You also don't need to use provided `<Stage>` component, it is available out of convenience. If you don't need react-dom at all then it's better to [render without it](https://github.com/michalochman/react-pixi-fiber#without-reactdom) by instantiating Pixi Application and setting the options there.
