### ISSUE TITLE
Rendering creates a lot of listeners (which also are leaking?)

### ISSUE THREAD

**Issue by ironchestgames** [michalochman/react-pixi-fiber#70]
### Description
I created a new project with create-react-app and added the minimum reqs to get React and Pixi working together (I love react-pixi-fiber btw.) Then I use the shared ticker from the Pixi app to update a state in a React Component. This causes a lot of listeners to be created (6 per frame) and what seems to be a memory leak as the heap grows.

I tried not rendering anything and then it seems to not leak.

### Steps to reproduce

1. check out https://github.com/ironchestgames/pixi-ticker-leak
2. run it with npm start
3. run profiling in devtools
Result: the heap grows when rendering, and it never comes down to original level

### Additional info

- react-pixi-fiber version: react-pixi-fiber@0.4.9
- React version: react@16.4.2
- ReactDOM version: react-dom@16.4.2
- PixiJS version: pixi.js@4.8.1

**Comment by michalochman** [comment]
Thanks for detailed report, I’ll have a look

**Comment by michalochman** [comment]
I had a brief look and I can see listeners created on each render, but on my machine they rise to about 2000 and are eventually collected by garbage collector (every couple seconds) returning to normal. It looks like this only happens in development mode though. When you run production build you will not be able to reproduce it – just run `npm build` and serve contents of `build` folder to see for yourself.

I wonder if this is the case here: https://github.com/facebook/react/issues/12141#issuecomment-362737894

**Comment by ironchestgames** [comment]
Thanks for looking in to this. I'm seeing the same thing as you, no listeners adding up when built.

It could be quite inconvenient though, to have to build that often. But in my project where I encountered this first I probably do something else that causes my leaks, so it's fine with me to close this issue.
