### ISSUE TITLE
How can I use typescript for this? 

### ISSUE THREAD

**Issue by congtung10t2** [michalochman/react-pixi-fiber#8]
I wanna set up this for a long term project so I choose typescript. But as I see, currently it support as well for js, jsx only.

**Comment by michalochman** [comment]
You would most likely need to create type definitions for your TypeScript project. I did not plan to do this yet, but it should not be too complicated to add yourself.

As a side note, this library is not production ready yet.

**Comment by michalochman** [comment]
@congtung10t2 thanks to #16 by @jmfirth you should be now able to use this library with TypeScript.
