### ISSUE TITLE
Window Missing on Server-side Rendering

### ISSUE THREAD

**Issue by KylePalko** [michalochman/react-pixi-fiber#87]
### Description

I'm implementing server-side rendering while leveraging `react-pixi-fiber`, but I'm getting an error (that makes sense) that the window, navigator, document, etc. objects are not available. I've come up with a workaround for this by replace `react-pixi-fiber` in the Webpack build process—basically I stubbed out the `<Stage />` component and had it just return `this.props.children`. This seems to work fine for me, but I was curious if you would be interested in a PR to resolve this issue, or if you'd rather not support SSR.

### Steps to reproduce

1. Setup SSR for React (I used express)
2. Add <Stage /> from `react-pixi-fiber`
3. Use Webpack to transpile/build

### Additional info

- react-pixi-fiber version: 0.6.2
- React version: 16.6.3
- ReactDOM version: 16.6.3
- PixiJS version: 4.8.2

**Comment by michalochman** [comment]
Hi @KylePalko, it should be fairly easy to fix for server-side rendering by lazy loading the `Stage` (this is now very easy with React 16.6+) and rendering it behind a flag that checks if the render is within browser context. The other issue is that PixiJS itself probably needs a window object so it would need to be lazily imported as well.

However, I understand this might be an unnecessary boilerplate so I am open to receiving a pull request that solves this without having to change the app code. See #80 for more context. Please note that stubbing `Stage` to return children is probably not the best idea – for SSR it would be better to just render the `canvas` element with its props and skip the logic related to instantiating PixiJS Application and react-pixi-fiber rendering.

**Comment by KylePalko** [comment]
`React.lazy` isn't available for SSR yet :/ The React docs point towards using [Loadable Components](https://github.com/smooth-code/loadable-components) module though. Is that what you were imaginging?

>  for SSR it would be better to just render the canvas element with its props and skip the logic related to instantiating PixiJS Application and react-pixi-fiber rendering.

Can you give me a bit of direction on how this might work? How would I render the `canvas` element server-side? You're blowing my mind here man XD

**Comment by michalochman** [comment]
@KylePalko ah, you're right, lazy is not in SSR yet.

> How would I render the canvas element server-side

Stage [already renders](https://github.com/michalochman/react-pixi-fiber/blob/b0229832dba4d071db00ef67c3cdd3459324ba57/src/Stage.js#L109) `canvas` element so probably nothing to change here.

I think all that's really needed is:
1. Not loading PIXI if not in browser context. This would probably mean changing [this import](https://github.com/michalochman/react-pixi-fiber/blob/b0229832dba4d071db00ef67c3cdd3459324ba57/src/Stage.js#L3) to require behind `if` condition.
2. Changing [Stage's componentDidMount](https://github.com/michalochman/react-pixi-fiber/blob/b0229832dba4d071db00ef67c3cdd3459324ba57/src/Stage.js#L59) to no-op if not in browser context.

**Comment by KylePalko** [comment]
Sweet, thanks for the direction, I will take a look. Again, appreciate all the work you've put into this!

**Comment by michalochman** [comment]
See if the solution in [this comment](https://github.com/michalochman/react-pixi-fiber/issues/80#issue-376322396) fits.
