### ISSUE TITLE
Remove canvas-prebuilt from devDependencies?

### ISSUE THREAD

**Issue by matthieu-foucault** [michalochman/react-pixi-fiber#94]
### Description

- When running `npm install` on the master branch, I get a 404 error because the tar.gz of `canvas-prebuilt` is not found for `node-v67-linux-x64`

- According to https://github.com/node-gfx/node-canvas-prebuilt
> the canvas-prebuilt package is deprecated. As of version 2, canvas itself bundles prebuilt versions from this repo. 

- Finally, I coudn't find any use of `canvas-prebuilt` or `canvas`. Is it actually used?

### Steps to reproduce

1. `npm install`
2. :boom:

**Comment by michalochman** [comment]
Hi @matthieu-foucault, feel free to open PR to replace `canvas-prebuilt` with `canvas`. We need `canvas` to be available to `jsdom` in unit tests.
